<div class='alert' style='background-color: #1c1a1e; color: #f5f4f0; padding:16px 26px; border-radius:20px; font-size:40px;'><B>Project Name</b> - First Notebook </div>
<div style='margin:0px 26px; color:#1c1a1e; font-size:16px;'>
<ol>
<li><B>Notebook Documentation</B>: Documenting a Jupyter Notebook is crucial for ensuring that the analysis it contains is understandable and reproducible, not only by others but also by your future self.  
Best practices in documentation start with a clear, informative introduction: what the notebook aims to achieve, the dataset being used, and any prerequisite knowledge or context needed to follow the analysis.  
Each cell, especially those containing key computations or decisions, should be accompanied by Markdown cells explaining the rationale behind the code, any assumptions made, and a summary of the results. Inline comments within the code cells can clarify complex lines of code or non-obvious steps.  
Visualizations should include titles, axis labels, and legends where appropriate to make them self-explanatory. Finally, the notebook should conclude with a summary of findings, any conclusions drawn, and possible next steps. This narrative structure turns your notebook from a mere collection of code cells into a coherent story about your data analysis journey.
</ol>
</div>

# Libraries & Data

In [1]:
# Importing default Libraries
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import seaborn as sns
import warnings
import datetime 
import os 

pd.options.display.max_rows = 1000
pd.options.display.max_columns = 1000

# Hi-resolution Plots and Matplotlib inline
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

# Set the maximum number of rows and columns to be displayed
warnings.filterwarnings('ignore')

# "magic commands" to enable autoreload of your imported packages
%load_ext autoreload
%autoreload 2

## Loading Data

In [39]:
data = pd.read_csv('../data/data.csv')
data.head(2)

,Vaccination type,Patient ID,Date of birth,Surname,Event date,Event done at ID,Patient Count
0,Cholera 2,27861537,18-Nov-1992,Stanley,16-Mar-2015,NaN,1
1,Measles/Mumps/Rubella 1,41183583,29-Mar-2013,Ferreira,22-Apr-2014,E87750,1

In [62]:
gms = pd.read_csv('../data/gms.csv')
reg_list = gms['Patient ID'].to_list()
reg_list

[52702,
 65293,
 2457891,
 1201808,
 1237456,
 1678856,
 1662154,
 1690694,
 1776589,
 1818640,
 1499541,
 1409894,
 2017998,
 3317543,
 3709292,
 3689361,
 3922932,
 10776440,
 9978428,
 10453520,
 11705499,
 11649497,
 11807477,
 4404601,
 4850765,
 4851120,
 4633876,
 4984559,
 6816605,
 7128980,
 5753135,
 6217264,
 13073262,
 14911780,
 14916520,
 15031590,
 15711584,
 14218021,
 16196817,
 34093107,
 34304517,
 33939151,
 35850226,
 36383580,
 36055714,
 35099658,
 35115361,
 36882197,
 37241138,
 37299255,
 42134636,
 42342978,
 42367664,
 44325331,
 43549424,
 43635223,
 43408435,
 43359182,
 43879409,
 43888000,
 45257790,
 45285847,
 45606448,
 45910918,
 38590189,
 38685152,
 39888829,
 39931993,
 40567329,
 39361717,
 39546808,
 39582030,
 39823161,
 40903412,
 41437091,
 41576169,
 46777785,
 46919404,
 46914629,
 46914617,
 46427679,
 46455773,
 46924390,
 47130170,
 48238713,
 48381176,
 48381704,
 48332029,
 48874815,
 48544396,
 48522449,
 49172205,
 49115309,
 49247197,
 47198783,
 47364891,
 47334681,
 47345843,
 47345991,
 47348279,
 47367636,
 47281654,
 47301497,
 47303418,
 47302313,
 47304788,
 47711789,
 47879684,
 47464227,
 47480989,
 47480990,
 47484755,
 47489539,
 47486471,
 47493466,
 47495733,
 47476044,
 47480085,
 47520921,
 47529643,
 47529442,
 47547726,
 47559531,
 47559975,
 47686041,
 47688373,
 47688733,
 47687277,
 47687448,
 47687023,
 47687224,
 47688803,
 47689558,
 47682392,
 47683914,
 47682790,
 47682822,
 47682886,
 47665133,
 48106807,
 48217330,
 49301251,
 49303165,
 49338300,
 49414435,
 49433766,
 49543282,
 49542329,
 49542331,
 49828630,
 49836137,
 49836458,
 49836616,
 49836607,
 49871571,
 49569699,
 49601731,
 49711786,
 49711565,
 49711690,
 49711972,
 49710404,
 49710415,
 49710901,
 49710904,
 49711189,
 49712808,
 49717685,
 49718996,
 49720792,
 49713793,
 49708654,
 49727207,
 49732740,
 49732821,
 49733223,
 49733391,
 49733400,
 49733281,
 49733454,
 49733005,
 49740559,
 49740163,
 49781244,
 50118118,
 50121651,
 50128384,
 50130754,
 50249436,
 50140571,
 50303714,
 50291001,
 16950837,
 16958236,
 16977522,
 16998145,
 17439321,
 17438294,
 17440772,
 17496802,
 17405310,
 17179237,
 17178147,
 3059358,
 1063849,
 1229992,
 1168486,
 1779751,
 1426360,
 1874977,
 1867669,
 3182712,
 3194545,
 3614143,
 4001671,
 4155096,
 9047961,
 8849192,
 10031142,
 10471896,
 11696804,
 11620780,
 12279076,
 4851831,
 4564011,
 5094453,
 7183401,
 7337660,
 5883416,
 6225048,
 7399175,
 8186453,
 12857101,
 12852247,
 13024938,
 13606258,
 14708948,
 15527534,
 15640102,
 13719720,
 14334275,
 14145904,
 16507397,
 33939515,
 36094333,
 36011912,
 35133178,
 35425000,
 37464475,
 42671557,
 44051573,
 44106653,
 44328194,
 43130987,
 43194805,
 43589956,
 43493051,
 43946339,
 43879440,
 45123094,
 45766441,
 45568800,
 38072586,
 38647884,
 38626939,
 38795549,
 39868838,
 40080211,
 39118031,
 39121513,
 39728161,
 41132285,
 41120017,
 41460870,
 41659889,
 41860341,
 46911524,
 46912021,
 46400740,
 46486337,
 46497204,
 46598916,
 46614906,
 46658827,
 46967893,
 46966457,
 47001000,
 47127014,
 47178606,
 48376647,
 48378321,
 48378868,
 48407523,
 48335084,
 48874012,
 48874842,
 48543514,
 48725663,
 49193772,
 49195355,
 49195354,
 49195358,
 49194982,
 49196968,
 49239719,
 49248016,
 49269450,
 49276567,
 47233768,
 47321422,
 47301365,
 47302954,
 47303347,
 47302268,
 47309036,
 47738814,
 47733854,
 47850989,
 47953192,
 47452758,
 47483474,
 47484155,
 47489253,
 47485131,
 47485843,
 47486637,
 47494195,
 47471999,
 47526461,
 47528474,
 47529495,
 47547360,
 47549040,
 47686567,
 47687930,
 47688494,
 47688542,
 47688275,
 47688692,
 47688857,
 47689292,
 47682068,
 47684227,
 47684156,
 47682666,
 47682828,
 48099327,
 49299654,
 49542325,
 49543233,
 49809592,
 49808907,
 49810846,
 49814380,
 49835810,
 49835518,
 49828118,
 49828629,
 49836671,
 49883265,
 49710196,
 49710615,
 49712488,
 49713133,
 49717552,
 49720225,
 49718610,
 49719295,
 49713913,
 49731578,
 49731575,
 49731510,
 49731656,
 49732847,
 49733384,
 49732999,
 49733014,
 49740306,
 49632705,
 49774750,
 49777522,
 49777571,
 49782654,
 50088379,
 50087092,
 50249434,
 16979544,
 17002120,
 17004945,
 17318413,
 17440105,
 17447430,
 17447432,
 17454648,
 17496679,
 17407389,
 17384998,
 17394347,
 17396800,
 17398233,
 17556268,
 17062395,
 17091847,
 17192148,
 17225692,
 17232501,
 52153,
 663219,
 2272611,
 1455542,
 1377443,
 1849770,
 1993787,
 3185947,
 3388705,
 8696811,
 9268604,
 10924943,
 11522822,
 10333506,
 11677810,
 12238293,
 12279081,
 11819464,
 4401802,
 4555665,
 6654974,
 5975546,
 5581457,
 6130900,
 8146269,
 13113136,
 13321339,
 13481941,
 15658709,
 14407328,
 14035188,
 15816530,
 36475985,
 36521667,
 36696746,
 36875730,
 37155766,
 41967166,
 42550043,
 42322641,
 42434209,
 43407289,
 43858155,
 45377572,
 45501629,
 38036938,
 38561475,
 38764596,
 39891757,
 40803478,
 39639468,
 41636907,
 46172135,
 46917119,
 46919033,
 46419380,
 46507707,
 46510557,
 46527427,
 46615928,
 46659153,
 46932593,
 46936154,
 46928535,
 46966369,
 46989321,
 47174705,
 48411996,
 48411989,
 48412168,
 48322065,
 48322614,
 48900079,
 48853733,
 49086084,
 49169680,
 47191028,
 47199535,
 47330878,
 47376661,
 47376663,
 47282887,
 47395441,
 47896697,
 47817525,
 47481384,
 47481892,
 47483102,
 47484038,
 47484059,
 47484276,
 47490120,
 47492839,
 47486705,
 47489013,
 47495305,
 47496209,
 47476374,
 47470609,
 47528938,
 47527101,
 47549377,
 47549479,
 47548340,
 47551305,
 47551304,
 47553278,
 47553241,
 47561203,
 47686559,
 47686600,
 47688440,
 47688557,
 47687446,
 47689089,
 47682512,
 47684290,
 47684299,
 47684149,
 47682792,
 47702924,
 49309934,
 49309028,
 49338292,
 49544007,
 49807843,
 49844114,
 49826279,
 49829473,
 49865676,
 50044348,
 49597850,
 49709921,
 49711326,
 49711862,
 49711943,
 49711488,
 49711579,
 49712175,
 49710903,
 49711199,
 49718520,
 49720976,
 49721030,
 49721332,
 49713773,
 49713885,
 49709116,
 49731579,
 49732714,
 49732741,
 49732915,
 49733389,
 49733305,
 49733412,
 49740531,
 49740583,
 49740633,
 49740197,
 49739133,
 49612281,
 49612696,
 49621911,
 49634012,
 49754551,
 50071970,
 50127888,
 50249406,
 50262077,
 50257634,
 50139538,
 16851588,
 16990894,
 17335014,
 17436803,
 17438564,
 17440269,
 17447428,
 17368720,
 17380275,
 17412297,
 17394091,
 17097498,
 17180934,
 17217871,
 17189843,
 17196937,
 17228046,
 17138545,
 17241624,
 17279210,
 17738204,
 17738197,
 17747182,
 17792371,
 17816145,
 18877156,
 19040905,
 19079013,
 19112512,
 19112529,
 19111513,
 19095274,
 635166,
 866143,
 2211432,
 1694508,
 1777100,
 1502702,
 1377306,
 1970148,
 4172155,
 8573740,
 8915985,
 10069380,
 9875457,
 4850626,
 4687444,
 4693107,
 5013733,
 6818164,
 6948189,
 6602245,
 6635822,
 5546087,
 8299755,
 12790559,
 13212906,
 12925174,
 14875793,
 14990450,
 14971235,
 13714546,
 14034475,
 16208998,
 34182340,
 34473256,
 36011521,
 34827633,
 35132164,
 36824964,
 37077490,
 37580070,
 37720529,
 42534986,
 42229003,
 42303232,
 44845959,
 43677691,
 43928953,
 38547950,
 39901801,
 40425755,
 40517712,
 40602426,
 40212471,
 39029988,
 39424486,
 39720144,
 39837324,
 41570649,
 41686589,
 46330972,
 46231801,
 46232175,
 46377890,
 46779756,
 46447789,
 46576780,
 46615199,
 46960551,
 48374562,
 48400459,
 48402522,
 48330769,
 48472326,
 48904138,
 48878329,
 48758699,
 49160987,
 49195349,
 49189507,
 49115304,
 49144043,
 49231079,
 49241432,
 49242104,
 49269838,
 47210621,
 47336856,
 47346146,
 47348153,
 47368194,
 47375329,
 47300900,
 47302262,
 47317085,
 47317087,
 47443295,
 47718862,
 47893813,
 47481296,
 47483217,
 47483287,
 47484824,
 47484950,
 47488409,
 47494193,
 47476061,
 47527697,
 47547873,
 47550563,
 47551256,
 47553701,
 47554307,
 47558915,
 47559338,
 47559785,
 47559790,
 47686038,
 47686514,
 47687975,
 47688740,
 47688978,
 47682642,
 47683816,
 47683840,
 47684000,
 49307829,
 49809811,
 49819306,
 49859283,
 49906943,
 49711873,
 49712025,
 49710188,
 49710402,
 49711073,
 49712518,
 49717697,
 49718185,
 49720227,
 49718559,
 49731517,
 49731634,
 49732716,
 49732767,
 49732766,
 49732940,
 49733355,
 49733315,
 49733458,
 49732964,
 49733013,
 49740167,
 49634588,
 49779325,
 49781273,
 49765312,
 50088251,
 50121764,
 50127165,
 50129637,
 50124645,
 50137973,
 50136972,
 50298087,
 16784572,
 16908023,
 16978535,
 17439834,
 17437892,
 17438456,
 17438143,
 17447221,
 17488423,
 17369877,
 17369083,
 17370373,
 17375747,
 17372764,
 17404399,
 17412292,
 17395439,
 17187465,
 17229438,
 17225909,
 17224825,
 17116961,
 17567398,
 17570885,
 17656732,
 17823901,
 18889679,
 19019823,
 18968159,
 19078546,
 19079043,
 19079144,
 19105742,
 19107568,
 19088229,
 19572151,
 19568692,
 19512167,
 19512214,
 83773,
 1229491,
 1670259,
 1805584,
 1375863,
 1555387,
 8447606,
 8595954,
 8631133,
 8647394,
 8711244,
 8826461,
 9349751,
 10202847,
 9952607,
 11979013,
 4781607,
 4783536,
 4851814,
 6763978,
 5367416,
 6144809,
 7904109,
 13118871,
 14809156,
 15137950,
 15519581,
 15665298,
 14116420,
 15952705,
 16195535,
 34340606,
 35764840,
 35921641,
 35086202,
 35488342,
 37614721,
 42125444,
 42073329,
 42642075,
 42734571,
 44110459,
 44601034,
 44524197,
 43637883,
 43721903,
 45215474,
 45400737,
 45920261,
 45989120,
 46116758,
 37862561,
 38152132,
 38258953,
 38561474,
 38721749,
 38722310,
 38654127,
 39904790,
 39994516,
 40636382,
 38804641,
 38931609,
 39239413,
 39783505,
 41048861,
 41135629,
 41645862,
 41798174,
 46499856,
 46613368,
 46973701,
 47180406,
 48395201,
 48426507,
 48319990,
 48354348,
 48433189,
 48458923,
 48853734,
 48508454,
 48594694,
 49239321,
 47354549,
 47348467,
 47374748,
 47299062,
 47284045,
 47301124,
 47302960,
 47301778,
 47301791,
 47317086,
 47842882,
 47483454,
 47484538,
 47489184,
 47490047,
 47491351,
 47493778,
 47496008,
 47476119,
 47519553,
 47519219,
 47519269,
 47519590,
 47521457,
 47548315,
 47553952,
 47559223,
 47559618,
 47686114,
 47686743,
 47687957,
 47687655,
 47689411,
 47683711,
 47684501,
 47683249,
 47683016,
 47695903,
 48113907,
 49395332,
 49525137,
 49541359,
 49808897,
 49828636,
 49828248,
 49865551,
 49910397,
 49688685,
 49711462,
 49710840,
 49710469,
 49710503,
 49710532,
 49710519,
 49713181,
 49713225,
 49717766,
 49717799,
 49720309,
 49720226,
 49719086,
 49720516,
 49713776,
 49700889,
 49726280,
 49734645,
 49731621,
 49732829,
 49732937,
 49732921,
 49732946,
 49733232,
 49733386,
 49733369,
 49732972,
 49740627,
 49740278,
 49740229,
 49740222,
 49740354,
 49634810,
 49669815,
 49667647,
 49745924,
 50118193,
 50088989,
 50087327,
 50127410,
 50124586,
 50245538,
 50169059,
 16998151,
 17317875,
 17335528,
 17439662,
 17462073,
 17496206,
 17368542,
 17407834,
 17057946,
 17090197,
 17204744,
 17193731,
 17229710,
 17227381,
 ...]

In [64]:
new = data[data['Patient ID'].isin(reg_list)]

In [65]:
new

,Vaccination type,Patient ID,Date of birth,Surname,Event date,Event done at ID,Patient Count
602,Typhim VI - Single Dose Single,44328194,13-Oct-1978,Davies,10-Oct-2018,E87063,1
1045,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,07-Nov-2005,E87063,1
1046,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,10-Aug-2012,E87063,1
1250,Avaxim 1,44328194,13-Oct-1978,Davies,10-Oct-2018,E87063,1
1895,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,02-Nov-2007,E87063,1
2234,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,13-Oct-2009,E87063,1
2235,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,18-Nov-2022,E87762,1
2315,Priorix 1,30733688,04-Oct-1987,Hoxha,24-Mar-2022,E87762,1
2322,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,10-Oct-2008,E87063,1
2633,Influenza Vaccine 1,44328194,13-Oct-1978,Davies,12-Feb-2007,E87063,1
3390,Influenza Vaccine 1,30733688,04-Oct-1987,Hoxha,18-Nov-2022,E87762,1
6156,Boostrix-IPV 1st Scheduled Booster,30733688,04-Oct-1987,Hoxha,31-Oct-2022,E87762,1
6457,Influvac sub-unit Tetra (Viatris formerly Myla...,30733688,04-Oct-1987,Hoxha,10-Sep-2020,E87762,1
6465,Quadrivalent influenza vaccine Split Virion in...,44328194,13-Oct-1978,Davies,08-Dec-2021,E87063,1
7057,Quadrivalent influenza vaccine Split Virion in...,44328194,13-Oct-1978,Davies,15-Oct-2020,E87063,1
7361,Comirnaty Omicron XBB.1.5 COVID-19 Vacc md via...,44328194,13-Oct-1978,Davies,23-Nov-2023,Elsewhere,1
7609,Quadrivalent influenza vaccine Split Virion in...,44328194,13-Oct-1978,Davies,15-Sep-2018,E87063,1
7712,Quadrivalent influenza vaccine Split Virion in...,44328194,13-Oct-1978,Davies,23-Oct-2019,E87063,1
8358,Cell-based quadrivalent Flu/Vac/SA inj 0.5ml p...,30733688,04-Oct-1987,Hoxha,29-Sep-2022,E87762,1
8571,Cell-based quadrivalent Flu/Vac/SA inj 0.5ml p...,44328194,13-Oct-1978,Davies,27-Sep-2022,E87762,1
9400,Revaxis 1,30733688,04-Oct-1987,Hoxha,22-Mar-2022,E87762,1
9645,Cell-based quadrivalent Flu/Vac/SA inj 0.5ml p...,44328194,13-Oct-1978,Davies,27-Sep-2023,E87762,1
10745,Revaxis 1,44328194,13-Oct-1978,Davies,10-Oct-2018,E87063,1

In [66]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 602 to 10745
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vaccination type  23 non-null     object
 1   Patient ID        23 non-null     int64
 2   Date of birth     23 non-null     object
 3   Surname           23 non-null     object
 4   Event date        23 non-null     object
 5   Event done at ID  23 non-null     object
 6   Patient Count     23 non-null     int64
dtypes: int64(2), object(5)
memory usage: 1.4+ KB

In [67]:
new.shape

(23, 7)

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12556 entries, 0 to 12555
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Vaccination type  12556 non-null  object
 1   Patient ID        12556 non-null  int64
 2   Date of birth     12556 non-null  object
 3   Surname           12556 non-null  object
 4   Event date        12556 non-null  object
 5   Event done at ID  11712 non-null  object
 6   Patient Count     12556 non-null  int64
dtypes: int64(2), object(5)
memory usage: 686.8+ KB

In [69]:
new.isna().sum()

Vaccination type    0
Patient ID          0
Date of birth       0
Surname             0
Event date          0
Event done at ID    0
Patient Count       0
dtype: int64

In [70]:
new.dropna(inplace=True)

In [71]:
new.isna().sum()

Vaccination type    0
Patient ID          0
Date of birth       0
Surname             0
Event date          0
Event done at ID    0
Patient Count       0
dtype: int64

In [32]:
new.shape

(23, 8)

# Exploratory Analysis